AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for cognito-app

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Runtime: java17
    Architectures:
      - x86_64
    Environment:
      Variables:
        USER_POOL_ID: !Ref CognitoUserPool
        CLIENT_ID: !Ref CognitoUserPoolClient

Resources:

  # 유저 풀 (회원 명부 - 회원 정보 저장)
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    # 스택 지워도 남겨두기. 수정이 필요해도 기존 정보 남겨두기.
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      # sam deploy 시 지정한 스택 이름을 가져다 사용
      UserPoolName: !Sub "${AWS::StackName}-userpool"
      # 로그인 아이디로 무엇을 사용할 것인가?
      # 기본 속성: sub(사용자 고유 ID, UUID 형태), email, name, given_name, family_name, phone_number 등
      UsernameAttributes:
        - email
      # 검증 수단으로 무엇을 사용할 것인가?
      # 회원 가입 시 Cognito가 검증용 이메일로 인증 코드 자동 발송
      AutoVerifiedAttributes:
        - email
      # 비밀번호 정책
      Policies:
        PasswordPolicy:
          MinimumLength: 8  # 비밀번호 최소 길이 8자
          RequireLowercase: false # 실습 편의를 위해 복잡도 완화
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
      # 사용할 유저 프로필 정보
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true  # 회원 가입 시 입력 필수
          Mutable: true  # 수정 가능

  # 유저 풀 클라이언트 (유저 풀에 접근할 수 있는 입구: 모바일용 or 웹사이트용 or 관리자용 등 여러 개 제작 가능)
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    # 스택 지워도 남겨두기. 수정이 필요해도 기존 정보 남겨두기.
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      ClientName: !Sub "${AWS::StackName}-client"
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false  # 비밀키(클라이언트 시크릿) 생성 안 함. 웹/모바일 앱은 비밀키를 안전하게 보관할 수 없으므로 false (필수)
      ExplicitAuthFlows:
        # 1. [보안 권장] Secure Remote Password 인증
        # AWS Amplify나 SDK를 쓰는 프론트엔드에서 주로 사용합니다.
        # 비밀번호가 네트워크를 타고 전송되지 않아 가장 안전합니다.
        - ALLOW_USER_SRP_AUTH

        # 2. [필수] 토큰 갱신 허용
        # Access Token(보통 1시간)이 만료되었을 때,
        # 사용자가 다시 로그인하지 않고도 Refresh Token으로 새 토큰을 받게 해줍니다.
        - ALLOW_REFRESH_TOKEN_AUTH

        # 3. [테스트/단순형] 일반 아이디/비번 인증
        # Postman, Curl 또는 간단한 HTTP 요청으로 로그인할 때 사용합니다.
        # 실제 운영(Production) 웹/앱에서는 SRP를 쓰는 게 좋지만,
        # 개발 중 테스트나 단순 구현을 위해 켜두는 것이 좋습니다.
        - ALLOW_USER_PASSWORD_AUTH

  # API Gateway
  CognitoRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      # 프론트 연결 대비
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'*'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'*'"
      Auth:
        # 기본 인증기 사용 안 함: 사용 시 Preflight 요청에서 401 unauthorized 발생
        # DefaultAuthorizer: MyCognitoAuthorizer

        # 인증기
        Authorizers:
          MyCognitoAuthorizer:  # 인증기 이름
            UserPoolArn: !GetAtt CognitoUserPool.Arn  # 유저 풀 연결
            IdentitySource: method.request.header.Authorization

  # 람다
  CognitoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: CognitoFunction
      Handler: com.example.user.UserProfileHandler::handleRequest
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /users/me
            Method: get
            RestApiId: !Ref CognitoRestApi
            # 인증이 필요한 람다(글 쓰기, 수정하기, 삭제하기 등)에만 Auth 추가
            Auth:
              Authorizer: MyCognitoAuthorizer

Outputs:

  # API Endpoint
  CognitoAppApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${CognitoRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/users/me"

  # 유저 풀 ID 출력 (관리자 강제 승인, 유저 삭제 등에서 필요)
  CognitoUserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref CognitoUserPool

  # 클라이언트 ID 출력 (회원 가입, 로그인 테스트 시 필요)
  CognitoClientId:
    Description: "Cognito User Pool Client ID"
    Value: !Ref CognitoUserPoolClient